### ISSUE TITLE
Rework all the UI

### ISSUE THREAD

**Issue by mertwole** [miniature-studios/miniature-happiness#57]
This is a tracking issue for complete UI rework
- [x] Inventory (including room descriptions shown on hover)
- [x] Boss tasks (also display complete tasks in list)
- [x] Boss stress
- [x] Money counter
- [x] Playback speed selector
- [x] Overlay selector
- [x] Room shop
- [x] Employee shop
- [x] Daily statistics window
- [x] Extended employee info
- [x] Win screen (after #137)
- [x] Lose screen (after #164)
- [x] `Not enough money` pop-up (after #172)
